# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ITIronMan' do
  use_frameworks!

  # Pods for ITIronMan
  pod 'Alamofire'
  pod 'SwiftCSV'
  pod 'Charts'
#  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :tag => 'v4.0.1'
  
  target 'ITIronManTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
